"""adding review to the schema

Revision ID: 81900618b3aa
Revises: 54c9ee0fed16
Create Date: 2022-03-04 22:46:48.291420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81900618b3aa'
down_revision = '54c9ee0fed16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_photos')
    # ### end Alembic commands ###
